### ISSUE TITLE
v1.11 is out: 3499 vorlines not found error

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-delaunay-voronoi#3]
Dear Asjad,

Thank you for your message.
I have updated delaunay, and tried to run this example:

`clear all`

`set obs 2000`

`gen x = runiform(0,100)`

`gen y = runiform(0,100)`

`drop if sqrt((x-50)^2 + (y-50)^2) > 50`

`local obs = _N `

`gen id = _n`

`mat drop _all`

`delaunay x y, triangles hull voronoi(lines)`

Which results in the following error message.

`Delaunay: Initializing >`

`Starting core routines >`

`Exporting geometry >`

`<istmt>: 3499 vorlines not found`

`r(3499);`

So, it looks like a glitch in the code somewhere.
I hope that you can find it.

Best,
Eric

**Comment by asjadnaqvi** [comment]
Dear Eric, thanks for reporting this! I have fixed this issue. Please check again with the new update.
